<body class="home_series">
    <script>
        document.title = "NETFLIX - Séries";

        $(".info_filme").css("display","none");
        $(".news-carousel").show(); 

        function hide_carousel_inicio(){
            $(".news-carousel").css("display","none"); 
            $(".info_filme").show();  
        }
        
        $(".nav").show();
        $("#filmes").removeClass("under");
        $("#inicio").removeClass("under");
        $("#tv").removeClass("under");
        $("#series").attr("class", "under");
    </script> 
    <div class="col-md-7  float-right cont_ajust">
        <h3>SÉRIES</h3>
        <div class="line line_series">
            <!--SÉRIES--> 
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Stranger%20Things&')" onmouseover="hide_carousel_inicio(); info('Stranger Things', '16', 'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.','Dublado', '2016', 'assets/images/series-capa/stranger_things_bg.jpg', 'MISTÉRIO');"><div class='box'><div id='box_img'> <img src='assets/images/series/stranger_things.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Anne%20Com%20Um%20E&')" onmouseover="hide_carousel_inicio(); info('Anne Com Um E', '12', 'O mundo de Green Gables que Anne tanto adora se expande com novas pessoas e emocionantes histórias de amor, perdas e amadurecimento.','Dublado', '2017', 'assets/images/series-capa/anne_com_um_e_bg.jpg', 'DRAMA');"><div class='box'><div id='box_img'> <img src='assets/images/series/anne_com_um_e.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Como%20defenfer%20um%20assassino&')" onmouseover="hide_carousel_inicio(); info('Como defenfer um assassino', '16', 'A história conta sobre um grupo de estudantes de Direito e sua professora de defesa criminal, que se vê envolvida em uma trama de assassinato que vai agitar toda a universidade e mudar o curso de suas vidas.','Dublado', '2014', 'assets/images/series-capa/como_defender_um_assassino_bg.jpg', 'CRIME');"><div class='box'><div id='box_img'> <img src='assets/images/series/como_defender_um_assassino.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Elite&')" onmouseover="hide_carousel_inicio(); info('Elite', '18', 'Após três jovens da escola pública serem transferidos para um conceituado colégio de elite, o conflito entre classes acaba levando a um assassinato.','Dublado', '2018', 'assets/images/series-capa/elite_bg.jpg', 'CRIME');"><div class='box'><div id='box_img'> <img src='assets/images/series/elite.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Eu%20Nunca...&')" onmouseover="hide_carousel_inicio(); info('Eu Nunca...', '12', 'Devi teve um ano complicado. Agora, tudo o que ela quer é ser popular. Será que os amigos, a família e seus sentimentos vão ajudar?','Dublado', '2020', 'assets/images/series-capa/eu_nunca_bg.jpg', 'COMÉDIA');"><div class='box'><div id='box_img'> <img src='assets/images/series/eu_nunca.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=O%20Político&')" onmouseover="hide_carousel_inicio(); info('O Político', '14', 'Payton não tem dúvidas de que chegará à presidência dos EUA. Para isso, ele precisa passar pelo cenário mais traiçoeiro de todos: a politicagem da escola.','Dublado', '2019', 'assets/images/series-capa/o_politico_bg.jpg', 'COMÉDIA');"><div class='box'><div id='box_img'> <img src='assets/images/series/o_politico.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Please%20Like%20Me&')" onmouseover="hide_carousel_inicio(); info('Please Like Me', '16', 'Após ser dispensado pela namorada, Josh sai do armário, passa a noite com um conhecido e volta para a casa da mãe.','Legendado', '2013', 'assets/images/series-capa/plaese_like_me_bg.jpg', 'COMÉDIA');"><div class='box'><div id='box_img'> <img src='assets/images/series/plaese_like_me.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Sex%20Education&')" onmouseover="hide_carousel_inicio(); info('Sex Education', '16', 'O inseguro Otis manja tudo quando o negócio é aconselhamento sexual, graças à sua mãe sexóloga. E aí a rebelde Maeve propõe criar uma clínica de terapia sexual na escola.','Dublado', '2019', 'assets/images/series-capa/sex_education_bg.jpg', 'COMÉDIA');"><div class='box'><div id='box_img'> <img src='assets/images/series/sex_education.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=The%20Walking%20Dead&')" onmouseover="hide_carousel_inicio(); info('The Walking Dead', '16', 'Nos Estados Unidos pós-apocalíptico, um pequeno grupo de sobreviventes segue viajando à procura de uma nova casa longe dos mortos-vivos.','Dublado', '2010', 'assets/images/series-capa/the_walking_dead_bg.jpg', 'FICÇÃO');"><div class='box'><div id='box_img'> <img src='assets/images/series/the_walking_dead.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Toy%20Boy&')" onmouseover="hide_carousel_inicio(); info('Toy Boy', '16', 'Após anos de prisão, um stripper ganha liberdade condicional e tenta provar, antes do novo julgamento, que sua amante armou para incriminá-lo pelo assassinato do marido.','Dublado', '2019', 'assets/images/series-capa/toy_boy_bg.jpg', 'MISTÉRIO');"><div class='box'><div id='box_img'> <img src='assets/images/series/toy_boy.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Stranger%20Things&')" onmouseover="hide_carousel_inicio(); info('Stranger Things', '16', 'Quando um garoto desaparece, a cidade toda participa nas buscas. Mas o que encontram são segredos, forças sobrenaturais e uma menina.','Dublado', '2016', 'assets/images/series-capa/stranger_things_bg.jpg', 'MISTÉRIO');"><div class='box'><div id='box_img'> <img src='assets/images/series/stranger_things.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Anne%20Com%20Um%20E&')" onmouseover="hide_carousel_inicio(); info('Anne Com Um E', '12', 'O mundo de Green Gables que Anne tanto adora se expande com novas pessoas e emocionantes histórias de amor, perdas e amadurecimento.','Dublado', '2017', 'assets/images/series-capa/anne_com_um_e_bg.jpg', 'DRAMA');"><div class='box'><div id='box_img'> <img src='assets/images/series/anne_com_um_e.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Como%20defenfer%20um%20assassino&')" onmouseover="hide_carousel_inicio(); info('Como defenfer um assassino', '16', 'A história conta sobre um grupo de estudantes de Direito e sua professora de defesa criminal, que se vê envolvida em uma trama de assassinato que vai agitar toda a universidade e mudar o curso de suas vidas.','Dublado', '2014', 'assets/images/series-capa/como_defender_um_assassino_bg.jpg', 'CRIME');"><div class='box'><div id='box_img'> <img src='assets/images/series/como_defender_um_assassino.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Elite&')" onmouseover="hide_carousel_inicio(); info('Elite', '18', 'Após três jovens da escola pública serem transferidos para um conceituado colégio de elite, o conflito entre classes acaba levando a um assassinato.','Dublado', '2018', 'assets/images/series-capa/elite_bg.jpg', 'CRIME');"><div class='box'><div id='box_img'> <img src='assets/images/series/elite.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Eu%20Nunca...&')" onmouseover="hide_carousel_inicio(); info('Eu Nunca...', '12', 'Devi teve um ano complicado. Agora, tudo o que ela quer é ser popular. Será que os amigos, a família e seus sentimentos vão ajudar?','Dublado', '2020', 'assets/images/series-capa/eu_nunca_bg.jpg', 'COMÉDIA');"><div class='box'><div id='box_img'> <img src='assets/images/series/eu_nunca.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=O%20Político&')" onmouseover="hide_carousel_inicio(); info('O Político', '14', 'Payton não tem dúvidas de que chegará à presidência dos EUA. Para isso, ele precisa passar pelo cenário mais traiçoeiro de todos: a politicagem da escola.','Dublado', '2019', 'assets/images/series-capa/o_politico_bg.jpg', 'COMÉDIA');"><div class='box'><div id='box_img'> <img src='assets/images/series/o_politico.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Please%20Like%20Me&')" onmouseover="hide_carousel_inicio(); info('Please Like Me', '16', 'Após ser dispensado pela namorada, Josh sai do armário, passa a noite com um conhecido e volta para a casa da mãe.','Legendado', '2013', 'assets/images/series-capa/plaese_like_me_bg.jpg', 'COMÉDIA');"><div class='box'><div id='box_img'> <img src='assets/images/series/plaese_like_me.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Sex%20Education&')" onmouseover="hide_carousel_inicio(); info('Sex Education', '16', 'O inseguro Otis manja tudo quando o negócio é aconselhamento sexual, graças à sua mãe sexóloga. E aí a rebelde Maeve propõe criar uma clínica de terapia sexual na escola.','Dublado', '2019', 'assets/images/series-capa/sex_education_bg.jpg', 'COMÉDIA');"><div class='box'><div id='box_img'> <img src='assets/images/series/sex_education.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=The%20Walking%20Dead&')" onmouseover="hide_carousel_inicio(); info('The Walking Dead', '16', 'Nos Estados Unidos pós-apocalíptico, um pequeno grupo de sobreviventes segue viajando à procura de uma nova casa longe dos mortos-vivos.','Dublado', '2010', 'assets/images/series-capa/the_walking_dead_bg.jpg', 'FICÇÃO');"><div class='box'><div id='box_img'> <img src='assets/images/series/the_walking_dead.jpg'></div></div></a>
            <a href="javascript:void(0)" onclick="load_serie('serie_selected.php?nome=Toy%20Boy&')" onmouseover="hide_carousel_inicio(); info('Toy Boy', '16', 'Após anos de prisão, um stripper ganha liberdade condicional e tenta provar, antes do novo julgamento, que sua amante armou para incriminá-lo pelo assassinato do marido.','Dublado', '2019', 'assets/images/series-capa/toy_boy_bg.jpg', 'MISTÉRIO');"><div class='box'><div id='box_img'> <img src='assets/images/series/toy_boy.jpg'></div></div></a>           
        </div>
    </div>
</body>       